### ISSUE TITLE
 Remove any additional and unnecessary forward slashes from the API URL

### ISSUE THREAD

**Issue by xlcici** [SumoLogic/sumologic-python-sdk#39]
The security services of Sumo API framework has been upgraded. API requests with multiple forward slashes (//) will receive a "500 Internal Server Error" response. Please remove any additional and unnecessary forward slashes from the API URL. Similar issue: https://github.com/SumoLogic/sumologic-python-sdk/issues/38

**Comment by mccartney** [comment]
Addressed in #40. Anything else would you recommend to improve @xlcici ?

**Comment by xlcici** [comment]
@mccartney Nope, Thank you!
