### ISSUE TITLE
Records always empty

### ISSUE THREAD

**Issue by zachlefevre** [SumoLogic/sumologic-python-sdk#56]
While using the search-job.py script the records returned are always:
```
{'fields': [{'name': '_count', 'fieldType': 'int', 'keyField': False}], 'records': []}
```
for query `* | count`
Using the UI I get many results.

Any suggestions?

**Comment by mjdsullivan** [comment]
did you use same time range between API and UI?  If using epoch for "to" and "from", make sure to use ms, not secs, since 1/1/1970.  If not using epoch, you must use ISO 8601 format.

**Comment by zachlefevre** [comment]
@mjdsullivan I was using seconds to epoch. Thank you
