### ISSUE TITLE
Put and Post definations

### ISSUE THREAD

**Issue by shivarajmulimani** [SumoLogic/sumologic-python-sdk#73]
Hi there,

I want to send logs using Sumologic-python-sdk.

I see there are two function in the code, which are  put and post.

Can anyone one explain me how to use them, what are the parameters it accepts and how I should send payload to particular collector source.

**Comment by kb18951452** [comment]
I "suspect" what you are seeing it the Helper functions 
'def put' and 'def post'

They are simply used as a helper in other functions in the SDK with put and post calls to the APIs. 
Search for "self.put" or "self.post" and you'll see how they are being used in the SDK.

**Comment by shivarajmulimani** [comment]
@kb18951452 Agreed with your point, yes I see them as helper function.

Is there any way to send logs/payload to particular collector source using python SDK.

Something like this - [https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/HTTP-Source/Upload-Data-to-an-HTTP-Source](https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/HTTP-Source/Upload-Data-to-an-HTTP-Source)
