### ISSUE TITLE
rest-python-client is a more appropriate name

### ISSUE THREAD

**Issue by sumoway** [SumoLogic/sumologic-python-sdk#8]
Need to look into whether and how we can change the name and if that will break anything.

**Comment by MelchiSalins** [comment]
Are you suggesting the package be renamed and drop "sumologic" completely out of it? The immediate concern that comes to my mind is people will not find the package as easily anymore.

**Comment by sumoway** [comment]
@MelchiSalins it was just a thought, and you've already pointed out a problem with it, thanks!
