### ISSUE TITLE
Bug on Search Job - does not work if autoParsingMode is not specified

### ISSUE THREAD

**Issue by upstart-swiss** [SumoLogic/sumologic-python-sdk#87]
AutoParsing Mode is getting passed as `null` causing incomprehensible 500 errors. From reaching out to sumo support this is because it's passing that null. 
This should either not be set if it's null (remove the key) or it should be set to either Manual or Automatic
https://github.com/SumoLogic/sumologic-python-sdk/blob/c76e56dff8cc0430e96abff593bac050d56c80fc/sumologic/sumologic.py#L151

**Comment by upstart-swiss** [comment]
Based on documentation about the defaults, this should be set to `'Manual'`

**Comment by himsharma01** [comment]
Thanks @upstart-swiss , for raising and fixing the issue.
