### ISSUE TITLE
fail to obtain job status

### ISSUE THREAD

**Issue by jpbottinelli** [SumoLogic/sumologic-python-sdk#9]
Hi, i'm trying to access a job that was successfully created, but I keep getting even though the create job returns 202 status

{
  "status" : 404,
  "id" : "D0FMU-CJDYR-H0VCO",
  "code" : "searchjob.jobid.invalid",
  "message" : "Job ID is invalid."
}

Thanks!

**Comment by sumoway** [comment]
Are you using one of the example scripts in the scripts folder?  Please email me directly at yoway@sumologic.com and I will help you troubleshoot.

**Comment by mritchie712** [comment]
@jpbottinelli you might be waiting too long in between the calls, you need to grab the results as soon as the job is finished, it only stays around for a few minutes (not sure about the exact timeframe).

**Comment by jpbottinelli** [comment]
Hi, thanks for your answer!
don't worry about it, a couple of weeks ago I that I already made it work.
Everything is ok now.

Regards

El sáb., 7 de mayo de 2016 10:53, mritchie712 <notifications@github.com>
escribió:

> @jpbottinelli <https://github.com/jpbottinelli> you might be waiting too
> long in between the calls, you need to grab the results as soon as the job
> is finished, it only stays around for a few minutes (not sure about the
> exact timeframe).
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/SumoLogic/sumologic-python-sdk/issues/9#issuecomment-217636442>
>
-- 
Juan Pablo Bottinelli Ortiz
Site Reliability Engineer
Site Reliability Engineering | ❖ Medallia, Inc.
www.medallia.com.ar/careers
Mobile: (+54) 1133108173
